name: Check dist

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-dist:
    name: Check dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: npm run build

      - name: Compare the expected and actual dist/ directories
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "::error::dist/ is out of sync with src/"
            git diff --stat dist/
            exit 1
          fi

      - name: Upload expected dist/ as artifact
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
